Repository cellml/libcellml, pull requests merged in 2021-07, with the labels that each got.

#889 Reform documentation for all assignId methods in the Annotator.
  src/api/libcellml/annotator.h
Labels: Documentation

#876 Privatise set parent
  CMakeLists.txt
  cmake/common.cmake
  src/CMakeLists.txt
  src/api/libcellml/analyser.h
  src/api/libcellml/analyserequation.h
  src/api/libcellml/analyserequationast.h
  src/api/libcellml/analyserexternalvariable.h
  src/api/libcellml/analysermodel.h
  src/api/libcellml/analyservariable.h
  src/api/libcellml/annotator.h
  src/api/libcellml/component.h
  src/api/libcellml/componententity.h
  src/api/libcellml/entity.h
  src/api/libcellml/generator.h
  src/api/libcellml/generatorprofile.h
  src/api/libcellml/importedentity.h
  src/api/libcellml/importer.h
  src/api/libcellml/importsource.h
  src/api/libcellml/issue.h
  src/api/libcellml/logger.h
  src/api/libcellml/model.h
  src/api/libcellml/namedentity.h
  src/api/libcellml/parentedentity.h
  src/api/libcellml/parser.h
  src/api/libcellml/printer.h
  src/api/libcellml/reset.h
  src/api/libcellml/types.h
  src/api/libcellml/units.h
  src/api/libcellml/validator.h
  src/api/libcellml/variable.h
  src/bindings/javascript/CMakeLists.txt
  src/bindings/javascript/parentedentity.cpp
  src/component.cpp
  src/component_p.h
  src/componententity.cpp
  src/componententity_p.h
  src/entity.cpp
  src/entity_p.h
  src/importsource.cpp
  src/model.cpp
  src/model_p.h
  src/namedentity.cpp
  src/namedentity_p.h
  src/parentedentity.cpp
  src/parentedentity_p.h
  src/reset.cpp
  src/reset_p.h
  src/units.cpp
  src/units_p.h
  src/variable.cpp
  src/variable_p.h
  tests/bindings/python/test_entity.py
Labels: Modified feature

#888 Add test where units are expected to be linked after parsing a model
  src/utilities.cpp
  tests/parser/file_parser.cpp
Labels: Bug

#897 Move ParentedEntities removeParent out of the public API.
  src/api/libcellml/parentedentity.h
  src/bindings/interface/parentedentity.i
  src/bindings/javascript/parentedentity.cpp
  src/component.cpp
  src/componententity.cpp
  src/model.cpp
  src/parentedentity.cpp
  src/parentedentity_p.h
  tests/bindings/python/test_entity.py
Labels: Bug

#891 Move addIssue and removeError to private implementation of Logger class
  src/CMakeLists.txt
  src/analyser.cpp
  src/annotator.cpp
  src/api/libcellml/analyser.h
  src/api/libcellml/annotator.h
  src/api/libcellml/importer.h
  src/api/libcellml/logger.h
  src/api/libcellml/parser.h
  src/api/libcellml/validator.h
  src/importer.cpp
  src/logger.cpp
  src/logger_p.h
  src/parser.cpp
  src/validator.cpp
Labels: Bug

#896 Add javascript tests for Reset.
  src/bindings/javascript/reset.cpp
  tests/bindings/javascript/CMakeLists.txt
  tests/bindings/javascript/reset.test.js
Labels: JavaScript bindings

#892 Move remove all issues
  src/analyser.cpp
  src/annotator.cpp
  src/api/libcellml/importer.h
  src/api/libcellml/logger.h
  src/api/libcellml/parser.h
  src/api/libcellml/validator.h
  src/bindings/interface/logger.i
  src/bindings/javascript/logger.cpp
  src/importer.cpp
  src/logger.cpp
  src/logger_p.h
  src/parser.cpp
  src/validator.cpp
  tests/bindings/python/test_issue.py
  tests/connection/connection.cpp
  tests/importer/importer.cpp
  tests/importer/model_flattening.cpp
  tests/parser/parser.cpp
Labels: Bug

#924 Disable Clang-Tidy by default
  CMakeLists.txt
Labels: Infrastructure

#927 CMake: mark `CLCACHE_EXE` as advanced
  cmake/environmentchecks.cmake
Labels: Infrastructure

#885 Remove InstallCommand from setup.in.py.
  src/bindings/python/setup.in.py
Labels: Python bindings

#898 Rename unsetOrder to removeOrder.
  src/api/libcellml/reset.h
  src/bindings/interface/reset.i
  src/bindings/javascript/reset.cpp
  src/reset.cpp
  tests/bindings/python/test_reset.py
  tests/reset/reset.cpp
Labels: Modified feature

#890 Fix Doxygen warnings
  src/analyserequationast.cpp
  src/parser.cpp
  src/utilities.h
  src/validator.cpp
  src/variable_p.h
Labels: Documentation

#903 Implement javascript tests for Units class.
  src/api/libcellml/units.h
  src/bindings/javascript/CMakeLists.txt
  src/bindings/javascript/importedentity.impl
  src/bindings/javascript/units.cpp
  tests/bindings/javascript/CMakeLists.txt
  tests/bindings/javascript/units.test.js
Labels: JavaScript bindings

#918 Implement javascript tests for Component class
  src/api/libcellml/component.h
  src/bindings/javascript/component.cpp
  src/component.cpp
  tests/bindings/javascript/CMakeLists.txt
  tests/bindings/javascript/component.test.js
Labels: JavaScript bindings

#886 Create analyser test showing segfault due to unlinked Units.
  src/analyser.cpp
  src/api/libcellml/issue.h
  src/issue.cpp
  tests/analyser/analyser.cpp
Labels: Bug

#919 Implement javascript tests for Parser class
  src/bindings/javascript/component.cpp
  src/bindings/javascript/parser.cpp
  src/bindings/javascript/units.cpp
  tests/bindings/javascript/CMakeLists.txt
  tests/bindings/javascript/parser.test.js
Labels: JavaScript bindings

#944 CMake: make sure that the version of ClangFormat is properly determined
  cmake/environmentchecks.cmake
Labels: Infrastructure

#941 Generator: further refinements to the generated C code
  src/generator.cpp
  src/generatorprofile.cpp
  tests/bindings/python/test_generator_profile.py
  tests/generator/generator.cpp
  tests/generator/generatorprofile.cpp
  tests/resources/generator/algebraic_eqn_computed_var_on_rhs/model.c
  tests/resources/generator/algebraic_eqn_computed_var_on_rhs/model.external.c
  tests/resources/generator/algebraic_eqn_computed_var_on_rhs/model.external.h
  tests/resources/generator/algebraic_eqn_computed_var_on_rhs/model.h
  tests/resources/generator/algebraic_eqn_const_var_on_rhs/model.c
  tests/resources/generator/algebraic_eqn_const_var_on_rhs/model.h
  tests/resources/generator/algebraic_eqn_constant_on_rhs/model.c
  tests/resources/generator/algebraic_eqn_constant_on_rhs/model.h
  tests/resources/generator/algebraic_eqn_derivative_on_rhs/model.c
  tests/resources/generator/algebraic_eqn_derivative_on_rhs_one_component/model.c
  tests/resources/generator/algebraic_eqn_state_var_on_rhs/model.c
  tests/resources/generator/algebraic_eqn_state_var_on_rhs_one_component/model.c
  tests/resources/generator/cellml_mappings_and_encapsulations/model.c
  tests/resources/generator/cellml_state_initialised_using_variable/model.c
  tests/resources/generator/cellml_unit_scaling_constant/model.c
  tests/resources/generator/cellml_unit_scaling_constant/model.h
  tests/resources/generator/cellml_unit_scaling_rate/model.c
  tests/resources/generator/cellml_unit_scaling_state/model.c
  tests/resources/generator/cellml_unit_scaling_state_initialised_using_constant/model.c
  tests/resources/generator/cellml_unit_scaling_state_initialised_using_variable/model.c
  tests/resources/generator/cellml_unit_scaling_voi_direct/model.c
  tests/resources/generator/cellml_unit_scaling_voi_indirect/model.c
  tests/resources/generator/coverage/model.c
  tests/resources/generator/coverage/model.implementation.out
  tests/resources/generator/coverage/model.modified.profile.c
  tests/resources/generator/dependent_eqns/model.c
  tests/resources/generator/fabbri_fantini_wilders_severi_human_san_model_2017/model.c
  tests/resources/generator/garny_kohl_hunter_boyett_noble_rabbit_san_model_2003/model.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.algebraic.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.computed.constant.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.constant.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.dependent.algebraic.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.dependent.computed.constant.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.dependent.constant.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.dependent.state.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.external.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.state.c
  tests/resources/generator/noble_model_1962/model.c
  tests/resources/generator/ode_computed_var_on_rhs/model.c
  tests/resources/generator/ode_computed_var_on_rhs_one_component/model.c
  tests/resources/generator/ode_const_var_on_rhs/model.c
  tests/resources/generator/ode_const_var_on_rhs_one_component/model.c
  tests/resources/generator/ode_constant_on_rhs/model.c
  tests/resources/generator/ode_constant_on_rhs_one_component/model.c
  tests/resources/generator/ode_multiple_dependent_odes/model.c
  tests/resources/generator/ode_multiple_dependent_odes_one_component/model.c
  tests/resources/generator/ode_multiple_odes_with_same_name/model.c
  tests/resources/generator/sine_model_imports/model.c
Labels: Generator
