Repository cellml/libcellml, pull requests merged in 2021-06, with the labels that each got.

#836 Annotator: replace std::pair with AnyCellmlElement
  cmake/common.cmake
  src/CMakeLists.txt
  src/analyser.cpp
  src/analyserexternalvariable_p.h
  src/analysermodel.cpp
  src/analysermodel_p.h
  src/analyservariable.cpp
  src/analyservariable_p.h
  src/annotator.cpp
  src/anycellmlelement_p.h
  src/api/libcellml/annotator.h
  src/api/libcellml/importer.h
  src/api/libcellml/issue.h
  src/api/libcellml/logger.h
  src/api/libcellml/types.h
  src/bindings/interface/annotator.i
  src/bindings/interface/component.i
  src/bindings/interface/importer.i
  src/bindings/interface/issue.i
  src/bindings/interface/logger.i
  src/bindings/interface/types.i
  src/bindings/javascript/issue.cpp
  src/bindings/python/__init__.py
  src/generator_p.h
  src/importer.cpp
  src/internaltypes.h
  src/issue.cpp
  src/issue_p.h
  src/logger.cpp
  src/model.cpp
  src/model_p.h
  src/parser.cpp
  src/types.cpp
  src/utilities.cpp
  src/utilities.h
  src/validator.cpp
  tests/CMakeLists.txt
  tests/analyser/analyser.cpp
  tests/analyser/analyserunits.cpp
  tests/annotator/annotator.cpp
  tests/bindings/python/test_analyser.py
  tests/bindings/python/test_annotator.py
  tests/bindings/python/test_entity.py
  tests/bindings/python/test_importer.py
  tests/bindings/python/test_issue.py
  tests/bindings/python/test_parser.py
  tests/bindings/python/test_validator.py
  tests/coverage/coverage.cpp
  tests/issue/issue.cpp
  tests/issue/tests.cmake
  tests/logger/logger.cpp
  tests/logger/tests.cmake
  tests/parser/parser.cpp
  tests/test_utils.cpp
  tests/test_utils.h
  tests/validator/validator.cpp
Labels: Modified feature

#873 Make resolve imports method more robust
  CMakeLists.txt
  src/api/libcellml/importer.h
  src/importer.cpp
  tests/bindings/python/test_importer.py
  tests/importer/importer.cpp
Labels: Bug

#874 Update Emscripten bindings.
  src/api/libcellml/types.h
  src/bindings/javascript/CMakeLists.txt
  src/bindings/javascript/analyserequation.cpp
  src/bindings/javascript/analyservariable.cpp
  src/bindings/javascript/annotator.cpp
  src/bindings/javascript/entity.cpp
  src/bindings/javascript/importer.cpp
  src/bindings/javascript/issue.cpp
  src/bindings/javascript/logger.cpp
  src/bindings/javascript/parentedentity.cpp
  tests/bindings/javascript/CMakeLists.txt
Labels: JavaScript bindings

#880 Add assignId API for AnyCellmlElement.
  src/annotator.cpp
  src/api/libcellml/annotator.h
  tests/annotator/annotator.cpp
Labels: Modified feature

#875 Report errors from importing invalid models
  src/api/libcellml/issue.h
  src/api/libcellml/logger.h
  src/importer.cpp
  src/issue.cpp
  src/logger.cpp
  tests/coverage/coverage.cpp
  tests/importer/importer.cpp
  tests/resources/importer/components_missing_units.cellml
  tests/resources/importer/import_invalid_component.cellml
  tests/resources/importer/import_invalid_units.cellml
  tests/resources/importer/import_invalid_xml.cellml
  tests/resources/importer/invalid_model.cellml
  tests/resources/importer/not_even_proper.xml
Labels: Bug

#869 Python version update
  .github/workflows/deploy-on-release.yml
Labels: Infrastructure
