Repository cellml/libcellml, pull requests merged in 2023-01, with the labels that each got.

#1085 Update environmentchecks.cmake to handle newer LibXml2 CMake configuration.
  cmake/environmentchecks.cmake
Labels: Infrastructure

#1088 Fix for CI issues
  tests/CMakeLists.txt
Labels: Infrastructure

#1077 Analyser: reworked the analysis of a model with external variables
  src/analyser.cpp
  src/analyserequation.cpp
Labels: Analyser

#1110 Try using uLong for buffer size in uncompress.
  src/CMakeLists.txt
  src/configure/libcellmlconfig_p.in.h
  src/xmldoc.cpp
Labels: Bug

#1111 Set minimum OSX deployment target that supports std::any.
  CMakeLists.txt
Labels: Bug
