Repository cellml/libcellml, pull requests merged in 2023-10, with the labels that each got.

#1177 Resolve imports
  src/importer.cpp
  tests/importer/model_flattening.cpp
Labels: Bug

#1181 Set macOS 10.15 as the minimum deployment target for macOS.
  CMakeLists.txt
Labels: Infrastructure

#1179 Fix flattening segfault
  src/component.cpp
  src/importer.cpp
  tests/importer/model_flattening.cpp
  tests/resources/importer/HHComplete/GateModel.cellml
  tests/resources/importer/HHComplete/LeakageModel.cellml
  tests/resources/importer/HHComplete/MembraneModel.cellml
  tests/resources/importer/HHComplete/MembraneModelController.cellml
  tests/resources/importer/HHComplete/PotassiumChannelModel.cellml
  tests/resources/importer/HHComplete/SodiumChannelModel.cellml
Labels: Bug

#1184 Analyser: add support for unknown variables that have been marked as external
  src/analyser.cpp
  src/api/libcellml/analyserexternalvariable.h
  tests/generator/generator.cpp
  tests/resources/generator/unknown_variable_as_external_variable/model.c
  tests/resources/generator/unknown_variable_as_external_variable/model.cellml
  tests/resources/generator/unknown_variable_as_external_variable/model.h
  tests/resources/generator/unknown_variable_as_external_variable/model.py
Labels: Analyser

#1188 Update deploy script
  .github/workflows/deploy-on-release.yml
  tests/importer/model_flattening.cpp
Labels: Infrastructure

#1190 Update setup-msbuild to the latest version.
  .github/workflows/deploy-on-release.yml
Labels: Infrastructure

#1196 AnaylserModel: Fix loss of Units definition information
  docs/conf.in.py
  src/analyser.cpp
  src/analysermodel.cpp
  src/analysermodel_p.h
  src/api/libcellml/analysermodel.h
  src/importer.cpp
  tests/generator/generator.cpp
  tests/importer/model_flattening.cpp
  tests/resources/generator/cellml_slc_example/model.py
  tests/resources/generator/cellml_slc_example/slc_model.cellml
  tests/resources/generator/cellml_slc_example/slc_model_units_only.cellml
  tests/resources/generator/cellml_slc_example/units_BG.cellml
Labels: Analyser

#1200 Switch to using Here document
  .github/workflows/deploy-on-release.yml
Labels: Infrastructure
