Repository cellml/libcellml, pull requests merged in 2023-04, with the labels that each got.

#1142 Enable printer to print models that have multiple math documents in a single math container object
  src/parser.cpp
  src/printer.cpp
  tests/CMakeLists.txt
  tests/libxml2issues.2.9.10.h
  tests/libxml2issues.2.9.11.h
  tests/libxml2issues.2.9.4.h
  tests/math/math.cpp
  tests/model/model.cpp
  tests/parser/cellml_1_0.cpp
  tests/printer/printer.cpp
  tests/resources/cellml1X/cardiac_constant_simplified.cellml
  tests/resources/printer/component_with_multiple_math.cellml
Labels: Bug

#1146 Fix parsing of CellML 1.X models with multiple math in a component
  src/parser.cpp
  src/xmlutils.cpp
  src/xmlutils.h
  tests/parser/cellml_1_0.cpp
  tests/resources/cellml1X/cardiac_constant_simplified_alternative.cellml
Labels: Bug

#1145 Fix segfault when using Units::equivalent/compatible API
  src/units.cpp
  tests/units/units.cpp
Labels: Bug

#1149 CMake: fixed an issue with BINDINGS_PYTHON's value not being taken into account
  CMakeLists.txt
Labels: Infrastructure

#1135 Analyser/Generator: replace if...else statements with switch ones wherever possible
  src/analyser.cpp
  src/generator.cpp
Labels: Miscellaneous

#1147 Fix an issue when initialising a state variable using a variable instead of a constant
  src/analyser.cpp
  tests/generator/generator.cpp
  tests/resources/generator/variable_initialised_using_a_constant/model.c
  tests/resources/generator/variable_initialised_using_a_constant/model.cellml
  tests/resources/generator/variable_initialised_using_a_constant/model.h
  tests/resources/generator/variable_initialised_using_a_constant/model.py
Labels: Bug

#1127 Resolve branch coverage in annotator.cpp
  src/annotator.cpp
  tests/annotator/annotator.cpp
  tests/coverage/coverage.cpp
Labels: Coverage

#1133 Analyser/Generator: don't use weak pointers
  src/analyser.cpp
  src/analyserequation.cpp
  src/analyserequation_p.h
  src/analyserequationast.cpp
  src/analyserequationast_p.h
  src/analyserexternalvariable.cpp
  src/analyserexternalvariable_p.h
  src/analysermodel_p.h
  src/analyservariable.cpp
  src/analyservariable_p.h
  src/anycellmlelement_p.h
  src/generator.cpp
  src/generator_p.h
  src/internaltypes.h
  tests/coverage/coverage.cpp
  tests/generator/generator.cpp
Labels: Bug

#1128 Resolve branch coverage in validator.cpp
  src/debug.cpp
  src/debug.h
  src/validator.cpp
  tests/coverage/coverage.cpp
  tests/resources/coverage/invalidxmlids.cellml
  tests/validator/validator.cpp
Labels: Coverage

#1131 Analyser/Generator: added some `xxxAsString()` methods
  src/analyser.cpp
  src/analyserequation.cpp
  src/analyserequationast.cpp
  src/analyserexternalvariable.cpp
  src/analysermodel.cpp
  src/analyservariable.cpp
  src/annotator.cpp
  src/api/libcellml/analyser.h
  src/api/libcellml/analyserequation.h
  src/api/libcellml/analyserequationast.h
  src/api/libcellml/analyserexternalvariable.h
  src/api/libcellml/analysermodel.h
  src/api/libcellml/analyservariable.h
  src/api/libcellml/generator.h
  src/api/libcellml/generatorprofile.h
  src/bindings/interface/analyserequation.i
  src/bindings/interface/analyserequationast.i
  src/bindings/interface/analysermodel.i
  src/bindings/interface/analyservariable.i
  src/bindings/interface/generatorprofile.i
  src/bindings/interface/types.i
  src/bindings/javascript/analyserequation.cpp
  src/bindings/javascript/analyserequationast.cpp
  src/bindings/javascript/analysermodel.cpp
  src/bindings/javascript/analyservariable.cpp
  src/bindings/javascript/generatorprofile.cpp
  src/bindings/python/__init__.py
  src/generator.cpp
  src/generatorprofile.cpp
  src/importer.cpp
  src/issue.cpp
  src/model.cpp
  src/printer.cpp
  src/units.cpp
  src/units_p.h
  src/utilities.cpp
  src/utilities.h
  src/validator.cpp
  src/variable.cpp
  tests/analyser/analyser.cpp
  tests/bindings/javascript/analyserequation.test.js
  tests/bindings/javascript/analyserequationast.test.js
  tests/bindings/javascript/analysermodel.test.js
  tests/bindings/javascript/analyservariable.test.js
  tests/bindings/javascript/generatorprofile.test.js
  tests/bindings/python/test_analyser.py
  tests/bindings/python/test_generator_profile.py
  tests/coverage/coverage.cpp
  tests/generator/generator.cpp
  tests/generator/generatorprofile.cpp
Labels: Miscellaneous

#1151 Align assignAllIds with documentation
  src/annotator.cpp
  tests/annotator/annotator.cpp
  tests/bindings/javascript/annotator.test.js
  tests/bindings/python/test_annotator.py
  tests/resources/annotator/lots_of_duplicate_ids.cellml
Labels: Bug

#1154 GitHub Actions update
  .github/workflows/deploy-on-release.yml
Labels: Infrastructure

#1090 Analyser: don't optimise the order of variables and equations
  src/analyser.cpp
  tests/analyser/analyser.cpp
  tests/bindings/javascript/analysermodel.test.js
  tests/bindings/javascript/analyservariable.test.js
  tests/bindings/python/test_analyser.py
  tests/coverage/coverage.cpp
  tests/generator/generator.cpp
  tests/resources/coverage/generator/model.c
  tests/resources/coverage/generator/model.implementation.out
  tests/resources/coverage/generator/model.modified.profile.c
  tests/resources/coverage/generator/model.modified.profile.py
  tests/resources/coverage/generator/model.out
  tests/resources/coverage/generator/model.py
  tests/resources/generator/algebraic_eqn_computed_var_on_rhs/model.c
  tests/resources/generator/algebraic_eqn_computed_var_on_rhs/model.external.c
  tests/resources/generator/algebraic_eqn_computed_var_on_rhs/model.external.py
  tests/resources/generator/algebraic_eqn_computed_var_on_rhs/model.py
  tests/resources/generator/algebraic_eqn_const_var_on_rhs/model.c
  tests/resources/generator/algebraic_eqn_const_var_on_rhs/model.py
  tests/resources/generator/cell_geometry_model/model.c
  tests/resources/generator/cell_geometry_model/model.external.c
  tests/resources/generator/cell_geometry_model/model.external.py
  tests/resources/generator/cell_geometry_model/model.py
  tests/resources/generator/cellml_mappings_and_encapsulations/model.c
  tests/resources/generator/cellml_mappings_and_encapsulations/model.py
  tests/resources/generator/dependent_eqns/model.c
  tests/resources/generator/dependent_eqns/model.py
  tests/resources/generator/fabbri_fantini_wilders_severi_human_san_model_2017/model.c
  tests/resources/generator/fabbri_fantini_wilders_severi_human_san_model_2017/model.py
  tests/resources/generator/garny_kohl_hunter_boyett_noble_rabbit_san_model_2003/model.c
  tests/resources/generator/garny_kohl_hunter_boyett_noble_rabbit_san_model_2003/model.py
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.algebraic.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.algebraic.py
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.computed.constant.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.computed.constant.py
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.constant.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.constant.py
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.dependent.algebraic.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.dependent.algebraic.py
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.dependent.computed.constant.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.dependent.computed.constant.py
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.dependent.constant.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.dependent.constant.py
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.dependent.state.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.dependent.state.py
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.external.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.external.py
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.py
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.state.c
  tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.state.py
  tests/resources/generator/noble_model_1962/model.c
  tests/resources/generator/noble_model_1962/model.py
  tests/resources/generator/sine_model_imports/model.c
  tests/resources/generator/sine_model_imports/model.py
Labels: Analyser
