Repository cellml/libcellml, pull requests merged in 2024-11, with the labels that each got.

#1287 Deploy on release updates
  .github/workflows/deploy-on-release.yml
Labels: Infrastructure

#1291 Analyser: make sure that we are dealing with a power function when units maps are not dimensionless
  src/analyser.cpp
  tests/analyser/analyserunits.cpp
  tests/resources/analyser/units/power_values.cellml
Labels: Analyser

#1296 Replace use of mikehardy/buildcache-action@v2 with cscouto/buildcache-action@v1.
  .github/workflows/ci.yml
Labels: Infrastructure

#1250 SWIG: make it work with Clang 19
  src/analyserequationast.cpp
  src/bindings/interface/analyserequationast.i
Labels: Infrastructure

#1292 Fix static build and test on Linux.
  .github/workflows/ci.yml
  src/CMakeLists.txt
  src/bindings/CMakeLists.txt
  src/bindings/python/CMakeLists.txt
  tests/gtest/cmake/internal_utils.cmake
Labels: Infrastructure

#1299 Still require this undefine for older macOS.
  src/analyserequationast.cpp
Labels: Infrastructure

#1304 Fix segfault with imports across multiple directories
  src/debug.h
  src/importer.cpp
  tests/importer/model_flattening.cpp
  tests/resources/importer/periodicstimulus/components/INa.xml
  tests/resources/importer/periodicstimulus/components/stimulated.xml
  tests/resources/importer/periodicstimulus/components/units.xml
  tests/resources/importer/periodicstimulus/experiments/periodic-stimulus.xml
  tests/test_utils.cpp
Labels: Bug
